# Generated by Django 4.0.6 on 2022-07-24 22:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='contenido',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
