# Generated by Django 4.0.6 on 2022-07-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_libro_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='subtitulo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
