# Generated by Django 4.0.6 on 2022-07-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_alter_libro_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
