# Generated by Django 4.0.6 on 2022-07-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_libro_autor_alter_libro_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
